### ISSUE TITLE
BOA install fails on sql.sh.inc fork: Cannot allocate memory

### ISSUE THREAD

**Issue by lexsoft00** [omega8cc/boa#1314]
Hi,

I've tried the new BOA `(boa in-head local my@email.com mini php-7.1)` on Debian9 local VM with:
```
    vb.memory = "4096"
    vb.cpus = 3
```
It's getting stuck at:
```
    default: BOA [11:30:29] ==> INFO: Installing MariaDB...
    default: /opt/tmp/boa/lib/functions/sql.sh.inc: fork: Cannot allocate memory
    default:
    default: EXIT on error due to missing helpers
    default: Please try to run this script again in a few minutes
    default: Also, make sure that the outgoing connections via port 443 work
    default: Bye
    default:
    default: BOA in-head completed
```
